-d D:\docs\ostim\digital\gowin\hdmi_project\impl\gwsynthesis\dk_video.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst D:\docs\ostim\digital\gowin\hdmi_project\src\dk_video.cst
-cfg D:\docs\ostim\digital\gowin\hdmi_project\impl\pnr\device.cfg
-sdc D:\docs\ostim\digital\gowin\hdmi_project\src\dk_video.sdc
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 50.000
