create_clock -name I_clk -period 37.037 -waveform {0 18.518} [get_ports {I_clk}] -add

// serial_clk generated by Gowin_rPLL: 371.25 MHz for 720p (period = 2.6936 ns)
create_clock -name serial_clk -period 2.6936 -waveform {0 1.3468} [get_nets {serial_clk}] -add

// pix_clk = serial_clk / 5 via CLKDIV
create_generated_clock -name pix_clk -source [get_nets {serial_clk}] -master_clock serial_clk -divide_by 5 -add [get_nets {pix_clk}]
